StingerSoft\DoctrineEntitySearchBundle\Entity\Field:
  type: entity
  inheritanceType: SINGLE_TABLE
  discriminatorColumn:
    name: discr
    type: string
    length: 255
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    fieldName: 
      type: string
      length: 512
      nullable: false
    internalFieldValue:
      column: fieldValue 
      type: text
      nullable: false
    serialized:
      type: boolean
      nullable: false
  manyToOne:
    document:
      targetEntity: StingerSoft\DoctrineEntitySearchBundle\Entity\Document
      inversedBy: internalFields
      fetch: EAGER