parameters:
  stinger_soft.doctrine_entity_search.search_service.class: StingerSoft\DoctrineEntitySearchBundle\Services\SearchService
  stinger_soft.doctrine_entity_search.document.class: StingerSoft\DoctrineEntitySearchBundle\Entity\Document
  stinger_soft.doctrine_entity_search.field.class: StingerSoft\DoctrineEntitySearchBundle\Entity\Field

  
services:
  _defaults:
    autoconfigure: true
    autowire: true
    public: false


  stinger_soft.doctrine_entity_search.search_service:
    class: '%stinger_soft.doctrine_entity_search.search_service.class%'
    arguments:
      - '@knp_paginator'
      - '%stinger_soft.doctrine_entity_search.document.class%'
      - '%stinger_soft.doctrine_entity_search.field.class%'