parameters:
  stinger_soft.doctrine_entity_search.search_service.class: StingerSoft\DoctrineEntitySearchBundle\Services\SearchService
  stinger_soft.doctrine_entity_search.document.class: StingerSoft\DoctrineEntitySearchBundle\Entity\Document
  stinger_soft.doctrine_entity_search.field.class: StingerSoft\DoctrineEntitySearchBundle\Entity\Field

  
services:
  stinger_soft.doctrine_entity_search.search_service:
    class: '%stinger_soft.doctrine_entity_search.search_service.class%'
    arguments:
      - '%stinger_soft.doctrine_entity_search.document.class%'
      - '%stinger_soft.doctrine_entity_search.field.class%'
    calls:
      - [setContainer, ['@service_container']]